import { describe, it, expect } from "vitest";
import { TFile } from "obsidian";
import type { App } from "obsidian";
import { getNoteWikiLinks } from "../src/services/wikilink-service";

// getNoteWikiLinks reads from the metadata cache via an injected `app`. The
// fake App exposes only what the resolver touches: vault.getFileByPath (source
// note lookup), metadataCache.getFileCache (its cached links), and
// metadataCache.getFirstLinkpathDest (single-destination resolution). Fixtures
// are real stub-TFile instances so `resolved instanceof TFile` holds.

function tfile(path: string): TFile {
	const basename = path.split("/").pop()!.replace(/\.md$/, "");
	return new TFile(path, basename);
}

interface FakeLink {
	original: string;
	link: string;
	/** Auto-generated by Obsidian for section links; we must NOT use it as alias. */
	displayText?: string;
	startLine: number;
	endLine?: number;
}

function cacheLink(l: FakeLink) {
	const line = l.startLine;
	return {
		original: l.original,
		link: l.link,
		displayText: l.displayText,
		position: {
			start: { line, col: 0, offset: 0 },
			end: { line: l.endLine ?? line, col: 0, offset: 0 },
		},
	};
}

/**
 * Build a fake App. The source note is always "Src.md"; `links` are its cached
 * body links; `firstDest` maps a bare linkpath -> resolved TFile.
 */
function makeApp(
	links: FakeLink[],
	firstDest: Record<string, TFile> = {},
): App {
	const src = tfile("Src.md");
	return {
		vault: {
			getFileByPath: (p: string): TFile | null =>
				p === "Src.md" ? src : null,
		},
		metadataCache: {
			getFileCache: () => ({ links: links.map(cacheLink) }),
			getFirstLinkpathDest: (linkpath: string): TFile | null =>
				firstDest[linkpath] ?? null,
		},
	} as unknown as App;
}

describe("getNoteWikiLinks — source resolution", () => {
	it("returns [] when the note path does not resolve to a file", () => {
		const app = {
			vault: { getFileByPath: () => null },
			metadataCache: {},
		} as unknown as App;
		expect(getNoteWikiLinks(app, "Missing.md")).toEqual([]);
	});

	it("returns [] when the note has no cached links", () => {
		expect(getNoteWikiLinks(makeApp([]), "Src.md")).toEqual([]);
	});
});

describe("getNoteWikiLinks — filtering", () => {
	it("keeps wikilinks and drops markdown links", () => {
		const app = makeApp([
			{ original: "[[Foo]]", link: "Foo", startLine: 0 },
			{ original: "[md](other.md)", link: "other.md", startLine: 1 },
		]);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out).toHaveLength(1);
		expect(out[0].linkText).toBe("Foo");
	});

	it("drops in-document anchors [[#Heading]] (empty path)", () => {
		const app = makeApp([
			{ original: "[[#Heading]]", link: "#Heading", startLine: 0 },
		]);
		expect(getNoteWikiLinks(app, "Src.md")).toEqual([]);
	});

	it("scopes to the selection line range (inclusive), excluding out-of-range links", () => {
		const app = makeApp([
			{ original: "[[Before]]", link: "Before", startLine: 1 },
			{ original: "[[Inside]]", link: "Inside", startLine: 5 },
			{ original: "[[After]]", link: "After", startLine: 9 },
		]);
		const out = getNoteWikiLinks(app, "Src.md", { fromLine: 4, toLine: 6 });
		expect(out.map((l) => l.linkText)).toEqual(["Inside"]);
	});
});

describe("getNoteWikiLinks — parsing", () => {
	it("splits path and section via parseLinktext", () => {
		const app = makeApp([
			{
				original: "[[Foo#Bar]]",
				link: "Foo#Bar",
				displayText: "Foo > Bar",
				startLine: 0,
			},
		]);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out[0].linkText).toBe("Foo");
		expect(out[0].section).toBe("Bar");
	});

	it("takes the alias from original, ignoring the auto-generated displayText", () => {
		const app = makeApp([
			// section link: cache displayText is auto "Foo > Bar" but there is no alias
			{
				original: "[[Foo#Bar]]",
				link: "Foo#Bar",
				displayText: "Foo > Bar",
				startLine: 0,
			},
			// real alias
			{
				original: "[[Baz|qux]]",
				link: "Baz",
				displayText: "qux",
				startLine: 1,
			},
		]);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out[0].displayText).toBeUndefined();
		expect(out[1].displayText).toBe("qux");
	});

	it("dedupes by target|alias|section", () => {
		const app = makeApp([
			{ original: "[[Foo]]", link: "Foo", startLine: 0 },
			{ original: "[[Foo]]", link: "Foo", startLine: 1 },
			{
				original: "[[Foo|bar]]",
				link: "Foo",
				displayText: "bar",
				startLine: 2,
			},
		]);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out).toHaveLength(2);
		expect(out.map((l) => l.displayText)).toEqual([undefined, "bar"]);
	});
});

describe("getNoteWikiLinks — resolution", () => {
	it("sets resolvedPath from getFirstLinkpathDest", () => {
		const dest = tfile("folder/Foo.md");
		const app = makeApp(
			[{ original: "[[Foo]]", link: "Foo", startLine: 0 }],
			{
				Foo: dest,
			},
		);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out[0].resolvedPath).toBe("folder/Foo.md");
	});

	it("leaves resolvedPath undefined when unresolved", () => {
		const app = makeApp([
			{ original: "[[Missing]]", link: "Missing", startLine: 0 },
		]);
		const out = getNoteWikiLinks(app, "Src.md");
		expect(out[0].resolvedPath).toBeUndefined();
	});

	it("resolves the bare path (section stripped) for a section link", () => {
		const dest = tfile("Foo.md");
		const app = makeApp(
			[{ original: "[[Foo#Bar]]", link: "Foo#Bar", startLine: 0 }],
			{ Foo: dest },
		);
		const out = getNoteWikiLinks(app, "Src.md");
		// resolved via "Foo" (not "Foo#Bar"), section preserved separately
		expect(out[0].resolvedPath).toBe("Foo.md");
		expect(out[0].section).toBe("Bar");
	});
});
